import unittest
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
class BuilderTests(unittest.TestCase):
 def test_builder_shell(self):
  h=(ROOT/'index.html').read_text(encoding='utf-8')
  for x in ('id="planGrid"','id="scrollExtent"','data-tool="draw"','data-tool="move"','data-tool="erase"','id="backup"','id="restore"','id="redo"','id="resetSettings"','id="saveSettings"','id="settingEdgeBonus"','id="settingCenterWeight"','id="settingFrontWeight"','id="settingZoomStep"','id="settingSeatScale"','id="settingShowSeatNumbers"','id="settingShowAreaLabels"','id="settingShowGrid"','id="settingsDialog"','id="settingsButton"','data-kind="blocked"','id="modeAssign"','id="modeResult"','id="csvInput"','id="autoAssign"','id="floorTitle"','id="floorSubtitle"','id="seatTooltip"','id="assignedCount"','id="unassignedCount"','id="blockedCount"','id="seatStatusFilter"','id="groupFilter"','id="mapSearch"','id="mapLegend"','id="assignmentSummary"','id="groupPriorityCard"','id="groupPriorityList"','id="areaFilter"','id="areaSummaryCard"','id="areaSummaryList"','id="autoAssignPrimary"','id="resultGroupFilter"','id="resultStatusFilter"','id="resultSearch"','id="exportResultCsv"','id="printResult"','id="resultPeopleList"','id="unassignedList"','id="groupLegend"','id="bulkSelectionCard"','id="selectedSeatsCount"','id="clearSeatSelection"','id="clearSelectedAssignments"','id="bulkGroupSelect"','id="assignGroupToSelection"','id="moveGroupToSelection"','id="bulkSelectionStatus"','id="selectGroupSeats"','id="selectAreaSeats"','id="selectAvailableSeats"','id="invertSeatSelection"','id="selectRowSeats"','id="selectFilteredSeats"'): self.assertIn(x,h)
 def test_floor_style_geometry_editor(self):
  j=(ROOT/'src'/'app.js').read_text(encoding='utf-8')
  for x in ('function rect(','function areaAt(','localStorage.setItem','paintSeats',"viewport=$('#viewport')",'const newId=','globalThis.crypto.randomUUID','setPointerCapture','viewport.addEventListener(\'pointerdown\'','viewport.addEventListener(\'pointermove\'','finishDrag','blockedDrag','function applyBlockedToolCells','lostpointercapture','before:JSON.stringify(state)','function fitContent','function openSettings','function applySettings','function priorityOptions','function restoreStateSnapshot','function redoAction','function undoAction','DEFAULT_SETTINGS','function mergeTouching','function connectedComponents','function splitDisconnectedAreas','function adjacent','dragTip','gridWidth','gridHeight','grid.style.width','function drawGrid','function drawViewportGrid','function updateScrollExtent','viewport.addEventListener(\'scroll\'','normalizeHall','Math.max(.1','blocked','blockedSeats','function blockedKeySet','function pruneBlockedSeats','splitDisconnectedAreas();','AREA_TYPES','applyGridSize','minW=cells.length','snapshot();state.hall.gridWidth=nextW','colors[a.type]||colors.empty','canvas.getBoundingClientRect()','function eventCell','dataset.cell=key(c)','function parseCsv','function autoAssignPeople','function setMode','function assignSeat','function seatAreaName','function assignmentForSeat','function migrateAssignmentState','seatStorageKey','selectedSeat','editSelectedSeat','seatTooltip','function seatMatchesFilter','function refreshGroupFilter','function updateAssignmentSummary','function groupPriorityValue','function renderGroupPriorities','function normalizeGroupPriorities','groupPriorities','function seatingAreaNames','function refreshAreaFilter','function renderAreaSummary','function resultMatchesFilter','function refreshResultGroupFilter','function renderResultLists','function exportResultCsv','function groupColor','function renderGroupLegend','function updateBulkSelection','selectedSeats=new Set()','highlightedGroup','groupColors','assignmentSchema','function normalizeGroupColors','function refreshBulkGroupSelect','function assignGroupToSelected','ondblclick','finishAssignSelect','assignSelectDrag','function selectRowSeatNumbers','function selectAreaSeatNumbers','function selectGroupSeatNumbers','function selectSeatNumbers','function visibleAssignmentSeats','group-color','function unassignGroup','autoAssignPeople(targetGroup=null)','filtered-out','if(!rec||rec.blocked)return','seats.filter(s=>!s.blocked)','compact-mode','requestAnimationFrame(()=>{fitContent()','windowPriority','compareWindowPriority','compareSeatPriority','seatPriorityScore','horizontalSeatWindows'): self.assertIn(x,j)
 def test_numbering_rule(self):
  j=(ROOT/'src'/'app.js').read_text(encoding='utf-8');self.assertIn('function seatingBlocks',j);self.assertIn('(blockIndex+1)*1000+i+1',j);self.assertIn('blocked:blocked.has(key(c))',j)
 def test_python_launcher(self): self.assertIn('ThreadingTCPServer',(ROOT/'run.py').read_text(encoding='utf-8'))
if __name__=='__main__': unittest.main()
