const $=s=>document.querySelector(s);const seatLayer=$('#seatLayer'),objectLayer=$('#objectLayer'),canvas=$('#canvas'),viewport=$('#viewport');const STORAGE_KEY='seating-studio-project-v1';let zoom=1,pan={x:40,y:15},drag=null,selected=null,tool='select';
const state={seats:[],objects:[],hall:{name:'אולם חדש',grid:24,front:'top',columns:6,placesPerColumn:12,placesPerRow:6,rows:12,gap:70,placeType:'seat',rowCounts:[]}};let wizardStep=0;
function buildDemo(){let n=1;const blocks=[{x:95,y:145,cols:9,rows:16},{x:430,y:125,cols:8,rows:19},{x:735,y:145,cols:9,rows:16}];for(const b of blocks)for(let r=0;r<b.rows;r++)for(let c=0;c<b.cols;c++){if((r<2&&((c+r)%4===0))||(r>12&&c<r-12))continue;state.seats.push({id:String(n++),x:b.x+c*34,y:b.y+r*29,assigned:(n%11===0)?'משובץ '+n:'',locked:n%37===0})}}
function renderObjects(){objectLayer.innerHTML='';for(const o of state.objects||[]){const e=document.createElement('div');e.className='hall-object '+o.type+'-object'+(selected==='obj:'+o.id?' selected-object':'');e.style.left=o.x+'px';e.style.top=o.y+'px';e.style.width=o.w+'px';e.style.height=o.h+'px';e.textContent=o.label||objectName(o.type);e.onpointerdown=ev=>startObjectDrag(ev,o);e.onclick=ev=>{ev.stopPropagation();selectObject(o)};objectLayer.append(e)}}
function objectName(t){return({stage:'במה',aisle:'מעבר',empty:'שטח ריק',table:'שולחן',bench:'ספסל',block:'גוש'}[t]||t)}
function render(){seatLayer.innerHTML='';renderObjects();for(const s of state.seats){const e=document.createElement('button');e.className='seat'+(s.assigned?' assigned':'')+(s.locked?' locked':'')+(selected===s.id?' selected':'');e.textContent=s.id;e.style.left=s.x+'px';e.style.top=s.y+'px';e.dataset.id=s.id;e.dataset.type=s.type||'seat';e.title=s.assigned?s.id+' — '+s.assigned:'מקום '+s.id;e.onclick=ev=>{ev.stopPropagation();selectSeat(s.id)};seatLayer.append(e)}updateStats();applyTransform()}
function selectObject(o){selected='obj:'+o.id;render();$('#panelTitle').textContent=objectName(o.type);$('#panelSubtitle').textContent='עריכת רכיב באולם';$('#selection').innerHTML='<h3>'+objectName(o.type)+'</h3><div class="object-controls"><label>רוחב<input id="objW" type="number" value="'+o.w+'"></label><label>גובה<input id="objH" type="number" value="'+o.h+'"></label><label>כותרת<input id="objLabel" value="'+escapeHtml(o.label||'')+'"></label><button class="danger" id="deleteObj">מחק רכיב</button></div>';$('#objW').onchange=e=>{o.w=Math.max(20,+e.target.value||20);changed()};$('#objH').onchange=e=>{o.h=Math.max(20,+e.target.value||20);changed()};$('#objLabel').onchange=e=>{o.label=e.target.value;changed()};$('#deleteObj').onclick=()=>{state.objects=state.objects.filter(x=>x!==o);selected=null;changed();resetPanel()}}
function startObjectDrag(ev,o){if(tool!=='select')return;ev.stopPropagation();const sx=ev.clientX,sy=ev.clientY,ox=o.x,oy=o.y;const move=e=>{o.x=ox+(e.clientX-sx)/zoom;o.y=oy+(e.clientY-sy)/zoom;renderObjects()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);changed()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function resetPanel(){$('#panelTitle').textContent='האולם';$('#panelSubtitle').textContent='סקירה ועריכה';$('#selection').innerHTML='<h3>בחר מקום או רכיב</h3><p>לחיצה על רכיב במפה תפתח כאן את אפשרויות העריכה שלו.</p>'}
function selectSeat(id){selected=id;const s=state.seats.find(x=>x.id===id);render();$('#panelTitle').textContent='מקום '+s.id;$('#panelSubtitle').textContent=s.locked?'מקום נעול':'עריכת מקום';$('#selection').innerHTML='<h3>פרטי מקום</h3><label class="field">שם / משובץ<input id="personName" value="'+escapeHtml(s.assigned)+'" placeholder="ללא שיבוץ"></label><div class="actions"><button id="toggleLock">'+(s.locked?'בטל נעילה':'נעל מקום')+'</button><button id="clearSeat">פנה מקום</button></div>';$('#personName').onchange=e=>{s.assigned=e.target.value.trim();render();selectSeat(id)};$('#toggleLock').onclick=()=>{s.locked=!s.locked;render();selectSeat(id)};$('#clearSeat').onclick=()=>{s.assigned='';render();selectSeat(id)}}
function escapeHtml(v){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function changed(){saveLocal();render();$('#status').innerHTML='נשמר אוטומטית <span class="autosave">● LocalStorage</span>'}
function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function restoreLocal(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!d||!Array.isArray(d.seats))return false;state.seats=d.seats;state.objects=Array.isArray(d.objects)?d.objects:[];state.hall={...state.hall,...(d.hall||{})};return true}catch{return false}}
function addObject(type,x=380,y=250){const presets={stage:[320,60],aisle:[90,300],empty:[160,120],table:[100,100],bench:[180,45],block:[260,180]};const [w,h]=presets[type]||[120,80];const o={id:Date.now()+Math.random(),type,x,y,w,h,label:objectName(type)};state.objects.push(o);selected='obj:'+o.id;changed();selectObject(o)}
function updateStats(){const total=state.seats.length,assigned=state.seats.filter(s=>s.assigned).length;$('#seatCount').textContent=total;$('#assignedCount').textContent=assigned;$('#freeCount').textContent=total-assigned}
function applyTransform(){canvas.style.transform='translate('+pan.x+'px,'+pan.y+'px) scale('+zoom+')';$('#zoomLabel').textContent=Math.round(zoom*100)+'%'}
function setZoom(v){zoom=Math.max(.1,Math.min(1.5,v));applyTransform()}
$('#zoomIn').onclick=()=>setZoom(zoom+.1);$('#zoomOut').onclick=()=>setZoom(zoom-.1);$('#fit').onclick=()=>{const z=Math.min((viewport.clientWidth-40)/1100,(viewport.clientHeight-40)/760);zoom=Math.max(.1,Math.min(1.5,z));pan={x:20,y:20};applyTransform()};
viewport.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom+(e.deltaY<0?.08:-.08))},{passive:false});viewport.onpointerdown=e=>{if(e.target.closest('.seat'))return;drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging')};viewport.onpointermove=e=>{if(!drag)return;pan.x=drag.px+(e.clientX-drag.x);pan.y=drag.py+(e.clientY-drag.y);applyTransform()};viewport.onpointerup=()=>{drag=null;viewport.classList.remove('dragging')};
$('#search').oninput=e=>{const q=e.target.value.trim();document.querySelectorAll('.seat').forEach(el=>{const s=state.seats.find(x=>x.id===el.dataset.id);el.classList.toggle('dim',!!q&&!s.id.includes(q)&&!s.assigned.includes(q))})};
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool;$('#status').textContent='כלי פעיל: '+b.textContent;if(['stage','aisle','empty','table','bench','block'].includes(tool)){addObject(tool);tool='select';document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('active',x.dataset.tool==='select'))}});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#status').textContent='מצב: '+b.textContent});
$('#closeSelection').onclick=()=>{selected=null;resetPanel();render()};
$('#save').onclick=()=>{saveLocal();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='seating-studio.json';a.click();URL.revokeObjectURL(a.href)};
$('#load').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.seats))throw Error();state.seats=data.seats;state.objects=Array.isArray(data.objects)?data.objects:[];state.hall={...state.hall,...(data.hall||{})};selected=null;saveLocal();render();$('#status').textContent='הגיבוי שוחזר ונשמר מקומית'}catch{$('#status').textContent='קובץ מפה לא תקין'}};
$('#clearLocal').onclick=()=>{if(confirm('לאפס את הפרויקט המקומי?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};
$('#autoAssign').onclick=()=>{$('#status').textContent='מנוע השיבוץ יחובר בגל הבא'};
function renumberColumns(){
 const xs=[...new Set(state.seats.map(s=>s.x))].sort((a,b)=>a-b);
 state.seats.forEach(s=>{const col=xs.indexOf(s.x)+1;const same=state.seats.filter(x=>x.x===s.x).sort((a,b)=>a.y-b.y);s.id=String(col*1000+same.indexOf(s)+1)});
}
function buildFromWizard(){
 const h=state.hall;state.seats=[];const startX=120,startY=135,dx=34,dy=29;
 const counts=(h.rowCounts&&h.rowCounts.length?h.rowCounts:Array.from({length:h.rows},()=>h.placesPerRow));
 for(let r=0;r<counts.length;r++){const count=Math.max(0,+counts[r]||0);for(let c=0;c<count;c++)state.seats.push({id:'',x:startX+c*(dx+h.gap),y:startY+r*dy,assigned:'',locked:false,type:h.placeType||'seat'})}
 renumberColumns();state.objects=[{id:'stage-main',type:'stage',x:390,y:35,w:320,h:55,label:'במה'}];selected=null;saveLocal();render();setTimeout(()=>$('#fit').click(),0);
}
const wizardTitles=['הגדרות בסיס','מבנה ראשוני','שורות וסוג מקום','מספור הטורים','בדיקה וסיום'];
function wizardRender(){
 $('#wizardHint').textContent='שלב '+(wizardStep+1)+' מתוך 5 — '+wizardTitles[wizardStep];
 document.querySelectorAll('.wizard-progress i').forEach((x,i)=>x.classList.toggle('on',i<=wizardStep));
 $('#wizardBack').disabled=wizardStep===0;$('#wizardNext').textContent=wizardStep===4?'צור אולם':'הבא';
 const h=state.hall;
 if(wizardStep===0)$('#wizardBody').innerHTML='<div class="wizard-grid"><div class="wizard-card"><h3>האולם</h3><label>שם האולם<input id="hallName" value="'+escapeHtml(h.name)+'"></label><label>כיוון החזית<select id="front"><option value="top">למעלה</option><option value="bottom">למטה</option><option value="left">שמאל</option><option value="right">ימין</option></select></label></div><div class="wizard-card"><h3>משטח עבודה</h3><label>גודל רשת<input id="gridSize" type="number" min="10" max="80" value="'+h.grid+'"></label><p class="wizard-note">לאחר יצירת האולם יהיה אפשר להזיז, לשנות ולהוסיף אזורים באופן חופשי.</p></div></div>';
 if(wizardStep===1)$('#wizardBody').innerHTML='<div class="wizard-grid"><div class="wizard-card"><h3>מבנה התחלתי</h3><label>מספר שורות<input id="rows" type="number" min="1" max="200" value="'+h.rows+'"></label><label>ברירת מחדל — מקומות בשורה<input id="placesPerRow" type="number" min="1" max="200" value="'+h.placesPerRow+'"></label></div><div class="wizard-card"><h3>מרווח בין טורים</h3><label>שטח בין הטורים<input id="gap" type="number" min="0" max="400" value="'+h.gap+'"></label><p class="wizard-note">המרווח חזותי בלבד ואינו משנה את מספר הטור.</p></div></div>';
 if(wizardStep===2){const types=[['seat','כיסא'],['bench','ספסל'],['table','מקום ליד שולחן'],['standing','מקום כללי']];const rows=Array.from({length:h.rows},(_,i)=>'<div class="row-config"><b>שורה '+(i+1)+'</b><label>מקומות <input class="rowCount" data-row="'+i+'" type="number" min="0" max="200" value="'+(h.rowCounts[i]??h.placesPerRow)+'"></label><span></span></div>').join('');$('#wizardBody').innerHTML='<div class="wizard-grid"><div class="wizard-card"><h3>סוג המקום</h3><div class="type-options">'+types.map(t=>'<div class="type-option '+(h.placeType===t[0]?'active':'')+'" data-place-type="'+t[0]+'">'+t[1]+'</div>').join('')+'</div><p class="wizard-note">הסוג נשמר בכל מקום וניתן יהיה לערוך אזורים בנפרד.</p></div><div class="wizard-card"><h3>כמות מקומות בכל שורה</h3><div class="rows-editor">'+rows+'</div></div></div>';document.querySelectorAll('[data-place-type]').forEach(x=>x.onclick=()=>{h.placeType=x.dataset.placeType;wizardRender()})}
 if(wizardStep===3)$('#wizardBody').innerHTML='<div class="wizard-card"><h3>כלל המספור הקבוע</h3><p class="wizard-note">הטורים נספרים לפי המיקום הפיזי שלהם <b>משמאל לימין</b>. המרחק ביניהם אינו משנה דבר.</p><div class="number-example">Column 1000 → 1001, 1002, 1003...<br>Column 2000 → 2001, 2002, 2003...<br>Column 3000 → 3001, 3002, 3003...</div><p class="wizard-note">שורות באורכים שונים אינן משנות את מספר הטור. מקום קיים בכל טור מקבל את המספר הבא באותו טור.</p></div>';
 if(wizardStep===4){const total=(h.rowCounts.length?h.rowCounts:Array.from({length:h.rows},()=>h.placesPerRow)).reduce((a,b)=>a+(+b||0),0);$('#wizardBody').innerHTML='<div class="wizard-card"><h3>מוכן ליצירה</h3><p>שם: <b>'+escapeHtml(h.name)+'</b></p><p>'+h.rows+' שורות · '+total+' מקומות בסך הכול</p><p>סוג מקום: <b>'+({seat:'כיסא',bench:'ספסל',table:'מקום ליד שולחן',standing:'מקום כללי'}[h.placeType]||h.placeType)+'</b></p><p class="wizard-note">כל שורה יכולה להיות באורך שונה. המספור יחושב לפי הטורים משמאל לימין.</p></div>'};
}
function wizardSaveStep(){const h=state.hall;if(wizardStep===0){h.name=$('#hallName').value||'אולם חדש';h.grid=+$('\#gridSize').value||24;h.front=$('#front').value}if(wizardStep===1){h.rows=Math.max(1,+$('#rows').value||1);h.placesPerRow=Math.max(1,+$('#placesPerRow').value||1);h.gap=Math.max(0,+$('#gap').value||0);if(h.rowCounts.length!==h.rows)h.rowCounts=Array.from({length:h.rows},(_,i)=>h.rowCounts[i]??h.placesPerRow)}if(wizardStep===2){h.rowCounts=Array.from(document.querySelectorAll('.rowCount')).map(x=>Math.max(0,+x.value||0))}}
$('#openWizard').onclick=()=>{$('#wizard').classList.remove('hidden');wizardStep=0;wizardRender()};$('#wizardClose').onclick=()=>$('#wizard').classList.add('hidden');$('#wizardBack').onclick=()=>{wizardSaveStep();wizardStep=Math.max(0,wizardStep-1);wizardRender()};$('#wizardNext').onclick=()=>{wizardSaveStep();if(wizardStep<4){wizardStep++;wizardRender()}else{buildFromWizard();$('#wizard').classList.add('hidden');$('#status').textContent='האולם נוצר — המספור חושב משמאל לימין'}};wizardRender();
if(!restoreLocal()){buildDemo();renumberColumns();state.objects=[{id:'stage-main',type:'stage',x:390,y:35,w:320,h:55,label:'במה'}];saveLocal()}render();setTimeout(()=>$('#fit').click(),0);