const $=s=>document.querySelector(s);const seatLayer=$('#seatLayer'),canvas=$('#canvas'),viewport=$('#viewport');let zoom=1,pan={x:40,y:15},drag=null,selected=null,tool='select';
const state={seats:[]};
function buildDemo(){let n=1;const blocks=[{x:95,y:145,cols:9,rows:16},{x:430,y:125,cols:8,rows:19},{x:735,y:145,cols:9,rows:16}];for(const b of blocks)for(let r=0;r<b.rows;r++)for(let c=0;c<b.cols;c++){if((r<2&&((c+r)%4===0))||(r>12&&c<r-12))continue;state.seats.push({id:String(n++),x:b.x+c*34,y:b.y+r*29,assigned:(n%11===0)?'משובץ '+n:'',locked:n%37===0})}}
function render(){seatLayer.innerHTML='';for(const s of state.seats){const e=document.createElement('button');e.className='seat'+(s.assigned?' assigned':'')+(s.locked?' locked':'')+(selected===s.id?' selected':'');e.textContent=s.id;e.style.left=s.x+'px';e.style.top=s.y+'px';e.dataset.id=s.id;e.title=s.assigned?s.id+' — '+s.assigned:'מקום '+s.id;e.onclick=ev=>{ev.stopPropagation();selectSeat(s.id)};seatLayer.append(e)}updateStats();applyTransform()}
function selectSeat(id){selected=id;const s=state.seats.find(x=>x.id===id);render();$('#panelTitle').textContent='מקום '+s.id;$('#panelSubtitle').textContent=s.locked?'מקום נעול':'עריכת מקום';$('#selection').innerHTML='<h3>פרטי מקום</h3><label class="field">שם / משובץ<input id="personName" value="'+escapeHtml(s.assigned)+'" placeholder="ללא שיבוץ"></label><div class="actions"><button id="toggleLock">'+(s.locked?'בטל נעילה':'נעל מקום')+'</button><button id="clearSeat">פנה מקום</button></div>';$('#personName').onchange=e=>{s.assigned=e.target.value.trim();render();selectSeat(id)};$('#toggleLock').onclick=()=>{s.locked=!s.locked;render();selectSeat(id)};$('#clearSeat').onclick=()=>{s.assigned='';render();selectSeat(id)}}
function escapeHtml(v){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateStats(){const total=state.seats.length,assigned=state.seats.filter(s=>s.assigned).length;$('#seatCount').textContent=total;$('#assignedCount').textContent=assigned;$('#freeCount').textContent=total-assigned}
function applyTransform(){canvas.style.transform='translate('+pan.x+'px,'+pan.y+'px) scale('+zoom+')';$('#zoomLabel').textContent=Math.round(zoom*100)+'%'}
function setZoom(v){zoom=Math.max(.1,Math.min(1.5,v));applyTransform()}
$('#zoomIn').onclick=()=>setZoom(zoom+.1);$('#zoomOut').onclick=()=>setZoom(zoom-.1);$('#fit').onclick=()=>{const z=Math.min((viewport.clientWidth-40)/1100,(viewport.clientHeight-40)/760);zoom=Math.max(.1,Math.min(1.5,z));pan={x:20,y:20};applyTransform()};
viewport.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom+(e.deltaY<0?.08:-.08))},{passive:false});viewport.onpointerdown=e=>{if(e.target.closest('.seat'))return;drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging')};viewport.onpointermove=e=>{if(!drag)return;pan.x=drag.px+(e.clientX-drag.x);pan.y=drag.py+(e.clientY-drag.y);applyTransform()};viewport.onpointerup=()=>{drag=null;viewport.classList.remove('dragging')};
$('#search').oninput=e=>{const q=e.target.value.trim();document.querySelectorAll('.seat').forEach(el=>{const s=state.seats.find(x=>x.id===el.dataset.id);el.classList.toggle('dim',!!q&&!s.id.includes(q)&&!s.assigned.includes(q))})};
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool;$('#status').textContent='כלי פעיל: '+b.textContent});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#status').textContent='מצב: '+b.textContent});
$('#closeSelection').onclick=()=>{selected=null;$('#panelTitle').textContent='האולם';$('#panelSubtitle').textContent='סקירה ועריכה';$('#selection').innerHTML='<h3>בחר מקום במפה</h3><p>לחיצה על מקום תפתח כאן את פרטי המקום והמשובץ.</p>';render()};
$('#save').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='seating-studio.json';a.click();URL.revokeObjectURL(a.href)};
$('#load').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.seats))throw Error();state.seats=data.seats;selected=null;render();$('#status').textContent='המפה נטענה'}catch{$('#status').textContent='קובץ מפה לא תקין'}};
$('#autoAssign').onclick=()=>{$('#status').textContent='מנוע השיבוץ יחובר בגל הבא'};
buildDemo();render();setTimeout(()=>$('#fit').click(),0);