const enc=new TextEncoder(),dec=new TextDecoder();
const u16=(n)=>new Uint8Array([n&255,(n>>>8)&255]),u32=(n)=>new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);
function cat(parts){const len=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(len);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
const CRC_TABLE=(()=>{const t=new Uint32Array(256);for(let i=0;i<256;i++){let c=i;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[i]=c>>>0}return t})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=CRC_TABLE[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function xmlEsc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function colName(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
export function makeZip(entries){const locals=[],centrals=[];let offset=0;for(const [name,data] of entries){const nb=enc.encode(name),db=typeof data==='string'?enc.encode(data):data,crc=crc32(db);const local=cat([u32(0x04034b50),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(db.length),u32(db.length),u16(nb.length),u16(0),nb,db]);locals.push(local);centrals.push(cat([u32(0x02014b50),u16(20),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(db.length),u32(db.length),u16(nb.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nb]));offset+=local.length}const central=cat(centrals),body=cat(locals);return cat([body,central,u32(0x06054b50),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(central.length),u32(body.length),u16(0)])}
function sheetXml(rows){const body=rows.map((row,ri)=>'<row r="'+(ri+1)+'">'+row.map((v,ci)=>{const ref=colName(ci)+(ri+1);if(typeof v==='number'&&Number.isFinite(v))return'<c r="'+ref+'"><v>'+v+'</v></c>';return'<c r="'+ref+'" t="inlineStr"><is><t xml:space="preserve">'+xmlEsc(v)+'</t></is></c>'}).join('')+'</row>').join('');return'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+body+'</sheetData></worksheet>'}
export function buildXlsx(sheets){const names=Object.keys(sheets),entries=[];entries.push(['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'+names.map((_,i)=>'<Override PartName="/xl/worksheets/sheet'+(i+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>').join('')+'</Types>']);entries.push(['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>']);entries.push(['xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+names.map((n,i)=>'<sheet name="'+xmlEsc(n.slice(0,31))+'" sheetId="'+(i+1)+'" r:id="rId'+(i+1)+'"/>').join('')+'</sheets></workbook>']);entries.push(['xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+names.map((_,i)=>'<Relationship Id="rId'+(i+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+(i+1)+'.xml"/>').join('')+'</Relationships>']);names.forEach((n,i)=>entries.push(['xl/worksheets/sheet'+(i+1)+'.xml',sheetXml(sheets[n]) ]));return makeZip(entries)}
function findEocd(b){for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--)if(b[i]===0x50&&b[i+1]===0x4b&&b[i+2]===0x05&&b[i+3]===0x06)return i;return-1}
async function inflateRaw(data){if(typeof DecompressionStream==='undefined')throw Error('הדפדפן אינו תומך בפריסת XLSX דחוס');const ds=new DecompressionStream('deflate-raw'),stream=new Blob([data]).stream().pipeThrough(ds);return new Uint8Array(await new Response(stream).arrayBuffer())}
export async function unzip(buffer){const b=new Uint8Array(buffer),view=new DataView(b.buffer,b.byteOffset,b.byteLength),e=findEocd(b);if(e<0)throw Error('קובץ XLSX/ZIP לא תקין');const count=view.getUint16(e+10,true),centralOffset=view.getUint32(e+16,true),files=new Map();let p=centralOffset;for(let i=0;i<count;i++){if(view.getUint32(p,true)!==0x02014b50)throw Error('ZIP central directory פגום');const method=view.getUint16(p+10,true),comp=view.getUint32(p+20,true),nameLen=view.getUint16(p+28,true),extraLen=view.getUint16(p+30,true),commentLen=view.getUint16(p+32,true),localOffset=view.getUint32(p+42,true),name=dec.decode(b.slice(p+46,p+46+nameLen)),ln=view.getUint16(localOffset+26,true),le=view.getUint16(localOffset+28,true),start=localOffset+30+ln+le,chunk=b.slice(start,start+comp);let data;if(method===0)data=chunk;else if(method===8)data=await inflateRaw(chunk);else throw Error('שיטת דחיסה לא נתמכת: '+method);files.set(name,data);p+=46+nameLen+extraLen+commentLen}return files}
function parseXml(bytes){return new DOMParser().parseFromString(dec.decode(bytes),'application/xml')}
export async function readXlsx(buffer){const files=await unzip(buffer),workbook=files.get('xl/workbook.xml');if(!workbook)throw Error('לא נמצא workbook');const wb=parseXml(workbook),relsFile=files.get('xl/_rels/workbook.xml.rels'),rels=relsFile?parseXml(relsFile):null,relMap=new Map();if(rels)for(const r of rels.getElementsByTagName('Relationship'))relMap.set(r.getAttribute('Id'),r.getAttribute('Target'));let shared=[];const ss=files.get('xl/sharedStrings.xml');if(ss){const doc=parseXml(ss);shared=[...doc.getElementsByTagName('si')].map(si=>[...si.getElementsByTagName('t')].map(t=>t.textContent||'').join(''))}const result={};for(const sh of wb.getElementsByTagName('sheet')){const name=sh.getAttribute('name')||'Sheet',rid=sh.getAttribute('r:id')||sh.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id'),target=relMap.get(rid)||('worksheets/sheet'+sh.getAttribute('sheetId')+'.xml'),path=target.startsWith('/')?target.slice(1):'xl/'+target.replace(/^\.\//,''),bytes=files.get(path);if(!bytes)continue;const doc=parseXml(bytes),rows=[];for(const row of doc.getElementsByTagName('row')){const arr=[];for(const c of row.getElementsByTagName('c')){const ref=c.getAttribute('r')||'A1',letters=(ref.match(/[A-Z]+/)||['A'])[0];let ci=0;for(const ch of letters)ci=ci*26+(ch.charCodeAt(0)-64);ci--;const type=c.getAttribute('t'),v=c.getElementsByTagName('v')[0]?.textContent??'',inline=c.getElementsByTagName('is')[0];arr[ci]=type==='s'?shared[Number(v)]??'':type==='inlineStr'?[...inline.getElementsByTagName('t')].map(t=>t.textContent||'').join(''):v}rows.push(arr.map(x=>x??''))}result[name]=rows}return result}
export function downloadBytes(bytes,name,type='application/octet-stream'){const blob=new Blob([bytes],{type}),a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
